# we have a really simple setup here
# we use docker-compose only as a convenient way to specify docker build parameters via a yaml file
# you could as well use Dockerfile directly with `docker build` and config passed via command-line args
#
# tips:
#   - to run lndmanage from docker, you can use our wrapper script ./lndmanage.sh
#   - see other scripts in this folder, also check the docker section in the main readme

version: '3.7'

services:

  lndmanage:
    image: lndmanage
    container_name: lndmanage
    command: ["run-service"]
    network_mode: host
    build:
      context: ./lndmanage
      dockerfile: Dockerfile
      args:
        - LNDMANAGE_HOST_SRC_PATH=_src
    volumes:
      - $LND_HOME:/root/.lnd
      - $LNDMANAGE_CACHE_DIR:/root/lndmanage/cache
